### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by botbw** [Twizwei/in-n-out#2]
hi there, I got lots of `Module not found` errors when setting up from a raw environment (although they can be easily fixed by `pip install`), would you mind fixing this and testing setup from a new conda env?

**Comment by Twizwei** [comment]
Thanks for pointing this out! I've updated the dependencies in [requirements.txt](https://github.com/Twizwei/in-n-out/blob/main/requirements.txt) and installation instructions [here](https://github.com/Twizwei/in-n-out?tab=readme-ov-file#requirements).

Also, feel free to let me know if there are other dependency issues! Thank you :)
