### ISSUE TITLE
Any other preprocessing methods without Deep3DFaceRecon_pytorch?

### ISSUE THREAD

**Issue by botbw** [Twizwei/in-n-out#3]
Hey, the `Deep3DFaceRecon_pytorch` seems to be outdated and is not compatible with recent GPUs (i.e. GTX3090). Is there any other preprocessing methods besides this one? Otherwise could you please share the environment you are using?

**Comment by Twizwei** [comment]
Unfortunately, I haven't explored other face alignment methods, as the original EG3D used Deep3DFaceRecon_pytorch.
